import Navbar from "@/components/general/navbar";
import Sidebar from "@/components/general/sidebar";
import "@/styles/base/reset.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
import Footer from "@/components/general/footer";
import Search from "@/components/general/search";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mystic Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenTypes) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <Sidebar />
          <Search />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
