import Navbar from "@/components/general/navbar";
import Sidebar from "@/components/general/sidebar";
import "@/styles/base/reset.scss";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import { Providers } from "@/redux/provider";
import Footer from "@/components/general/footer";
import Cart from "@/components/shop/cart";
import ContactModal from "@/components/modal/contactModal";
import { Toaster } from "react-hot-toast";
import getCustomer from "@/actions/getCustomer";

const inter = Inter({ subsets: ["latin"] });
const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Mystic Shop",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: ChildrenTypes) {
  const customer = await getCustomer();

  return (
    <html lang="en">
      <body className={`${inter.className} ${playfair.className}`}>
        <Providers>
          <Navbar customer={customer} />
          <Sidebar />
          <Cart />
          <ContactModal />
          <Toaster />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
